# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# Trigger by pushes to the master branch
trigger:
- master

# Uses the Ubuntu linux base image
pool:
  vmImage: 'Ubuntu-16.04'

# Uses variables from the Variable Group 'Test Docker Demo' and sets the value of imageName
variables:
  - group: 'Test Docker Demo'
  - name: imageName
    value: 'azure-pipeline-docker-demo:$(build.buildId)'

# Scripts to build image, log in to custom registry and push to registry
steps:
- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
    docker login -u $(dockerId) -p $(docker-password) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
  displayName: 'docker build'
